### ISSUE TITLE
Production Build

### ISSUE THREAD

**Issue by sdzharkov** [longtranista/django-vue-webpack#5]
Any clue how to create a production ready build of the two? I want to publish my app but want django to serve the Vue/webpack frontend. 

Or do I have to basically run the front and back-end separately?

**Comment by longtranista** [comment]
Separating backend & frontend is only for development.
Once you want to publish your app, you need to build Vue/webpack by the command `npm run build` and then you only need to deploy the django webserver. 

Basically, this setup build on top of vuejs-template project (http://vuejs-templates.github.io/webpack/), I just config so the template can work with Django. 
For the frontend you can refer [This](http://vuejs-templates.github.io/webpack/) for the documenation.

**Comment by sdzharkov** [comment]
Great that makes sense. So I'm having a few problems running your application for development and production builds - the line "import Vue from 'vue'" can't actually import vue in main.js because the node module folder is in the base directory... any reason that you put all of the front-end code in the resources/assets/js directory?

**Comment by longtranista** [comment]
The frontend code I put it in resources/assets but I want to keep packpage.json & node_modules still at the root of the projects for better management. 
I will double check why import command not work and reply you very soon!

**Comment by longtranista** [comment]
I just fixed the configuration, now you can run Vue js as normal. 
Thanks!

**Comment by sdzharkov** [comment]
Awesome that totally works!

One more thing, have you tried running a production build and just running django? I assumed that after I built the front-end it should just serve it, but I receive this issue with Django 
**TemplateDoesNotExist at /
webapp/index.html**

It doesn't make sense because you have defined your index.html file and directed the view to it, but it still doesn't recognize it. Any thoughts?

**Comment by sdzharkov** [comment]
I just figured it out I'll push the change. You didn't have "webapp" included in your Installed Apps.

**Comment by longtranista** [comment]
Oh, I just forgot adding "webapp" to installed Apps, Thanks for your point outs! 
I have some private projects created based on this combination (Vuejs + Django) and already on production. They work great! 
If you have any discussion just contact me. @sdzharkov

**Comment by sdzharkov** [comment]
Awesome thank you! Do you have an email or some other form of contact I can reach you at? I'm trying to move my app to production but the app crashes and the browser becomes really slow. Not sure what exactly it is but I would love some guidance.

**Comment by longtranista** [comment]
Sure! 
You can reach me by email at longtm.it@gmail.com
Or my home page at http://longtm.co/
Have a nice day!
